version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # Aquí puedes agregar variables de entorno para tu backend si es necesario
      SPRING_PROFILES_ACTIVE: production
    restart: always  # Mantener siempre activo

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    environment:
      # Cambiar el entorno de la API para Angular
      API_URL: "http://localhost:8080"  # URL del backend
    restart: always  # Mantener siempre activo
